apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cheerful-warbler-python 
  janus-idp.io/tekton: cheerful-warbler-python
  backstage.io/kubernetes-id: cheerful-warbler-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cheerful-warbler-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  